// Top-level build file where you can add configuration options common to all sub-projects/modules.

ext {
    APPLICATION_ID = "ua.notky.silfy"

    MIN_SDK_VERSION = 24
    TARGET_SDK_VERSION = 31
    COMPILE_SDK_VERSION = 31

    VERSION_CODE = 1

    DEV_VERSION_NAME = '1.0.2'
    RELEASE_VERSION_NAME = '1.0.0'
}

buildscript {
    ext {
        // main
        kotlin_version = '1.7.0'
        gradle_version = '7.2.1'
        hilt_version = '2.42'
        nav_version = '2.4.2'
        coroutines_version = "1.5.0"
        core_ktx_version = "1.8.0"
        lifecycle_version = "2.4.1"

        // ui
        appcompat_version = "1.4.2"
        material_version = "1.6.1"
        activity_version = "1.4.0"
        constraint_version = "2.1.4"
        recycler_version = "1.2.1"

        // network
        retrofit_version = "2.9.0"
        okhttp_version = "4.9.0"
        moshi_version = "1.12.0"

        // libs
        glide_version = "4.12.0"
        picasso_version = "2.8"
        picasso_transform_version = "2.4.0"
        preference_version = "1.2.0"
        data_store_version = "1.0.0"
        paging_version = "3.1.1"
        room_version = "2.4.2"
        timber_version = "4.7.1"
        paging_version = "3.1.1"
        mapstruct_version = "1.5.2.Final"

        //tests
        junit_version = "4.13.2"
        junit_ext_version = "1.1.3"
        espresso_version = "3.4.0"
    }

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:$gradle_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.google.dagger:hilt-android-gradle-plugin:$hilt_version"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}